create table public.feeds_entry
(
    id               bigint generated by default as identity
        primary key,
    full_text        text                     not null,
    is_resolved      boolean                  not null,
    channel          varchar(255)             not null,
    extra_parameters text,
    timestamp        timestamp with time zone not null,
    is_geolocated    boolean                  not null,
    location         double precision[],
    epoch            bigint,
    reason           varchar(255)
);

alter table public.feeds_entry
    owner to postgres;

create index feeds_entry_epoch_idx
    on public.feeds_entry (epoch);

create table public.feeds_location
(
    id                   bigint generated by default as identity
        primary key,
    formatted_address    text,
    latitude             double precision not null,
    longitude            double precision not null,
    northeast_lat        double precision not null,
    northeast_lng        double precision not null,
    southwest_lat        double precision not null,
    southwest_lng        double precision not null,
    entry_id             bigint           not null
        constraint feeds_location_entry_id_2ef390e3_fk_feeds_entry_id
            references public.feeds_entry
            deferrable initially deferred,
    timestamp            timestamp with time zone,
    epoch                bigint           not null,
    reason               varchar(255),
    channel              varchar(255),
    extra_parameters     text,
    is_location_verified boolean default false,
    is_need_verified     boolean default false,
    is_deleted           boolean default false
);

alter table public.feeds_location
    owner to postgres;

create index feeds_location_entry_id_2ef390e3
    on public.feeds_location (entry_id);

create index feeds_location_northeast_lat_northeast_lng_idx
    on public.feeds_location (northeast_lat, northeast_lng);

create index feeds_location_northeast_lat_northeast_lng_southwest_lat_so_idx
    on public.feeds_location (northeast_lat, northeast_lng, southwest_lat, southwest_lng);

create index feeds_location_northeast_lng_idx
    on public.feeds_location (northeast_lng);

create index feeds_location_epoch_idx
    on public.feeds_location (epoch);

create index feeds_location_reason_epoch_idx
    on public.feeds_location (reason, epoch);

create index feeds_location_reason_idx1
    on public.feeds_location using gist (reason public.gist_trgm_ops);

create index feeds_location_is_deleted_idx
    on public.feeds_location (is_deleted);


-- Feeds Entry
INSERT INTO public.feeds_entry (id, full_text, is_resolved, channel, extra_parameters, timestamp, is_geolocated, location, epoch, reason) VALUES (1522020, '@alitekintr Harbiye Mahallesi Harbiye caddesi Defne/Hatay çadır ihtiyacı var acil olarak.', false, 'twitter', '{''user_id'': 36896375, ''screen_name'': ''Lacinok'', ''name'': ''Banu Ç'', ''tweet_id'': 1625220979738783749, ''created_at'': Timestamp(''2023-02-13 22:50:51''), ''hashtags'': None, ''user_account_created_at'': ''Banu Ç'', ''media'': None}', '2023-02-13 20:05:32.360011 +00:00', false, null, 1676328651, null);
INSERT INTO public.feeds_entry (id, full_text, is_resolved, channel, extra_parameters, timestamp, is_geolocated, location, epoch, reason) VALUES (1522019, e'HATAY/SAMANDAĞ ‼️

25-30 kisilik aile 6 cocuk,1 bebek var. Çadır ve ısıtıcı lazım, ilk günden beri serada kalıyorlar.
Mızraklı mahallesi kuşalanı caddesi no:55 Samandağ/Hatay
Telefon numarası:
0530 244 14 99 - Gökhan Küçük', false, 'twitter', '{''user_id'': 946308442326814720, ''screen_name'': ''beuyhrd'', ''name'': ''Beyza'', ''tweet_id'': 1625220504247214111, ''created_at'': Timestamp(''2023-02-13 22:48:58''), ''hashtags'': None, ''user_account_created_at'': ''Beyza'', ''media'': None}', '2023-02-13 20:05:29.632974 +00:00', false, null, 1676328538, null);
INSERT INTO public.feeds_entry (id, full_text, is_resolved, channel, extra_parameters, timestamp, is_geolocated, location, epoch, reason) VALUES (1522018, e'@fatihaltayli Teyit edildi: 13 şubat saat 22:45’te
Kurulan çadır düşmüş 7kişi için acil çadır lazım .
Adres Dumlupınar mahallesi 78 nolu sk no 47 parkın önü Şahinbey Gaziantep
Telefon:+90 (534) 553 97 44
Buse Çiçek', false, 'twitter', '{''user_id'': 1397514920808402947, ''screen_name'': ''Alicakir190300'', ''name'': ''Ali'', ''tweet_id'': 1625220645431681035, ''created_at'': Timestamp(''2023-02-13 22:49:31''), ''hashtags'': None, ''user_account_created_at'': ''Ali'', ''media'': None}', '2023-02-13 20:05:26.682806 +00:00', false, null, 1676328571, null);
INSERT INTO public.feeds_entry (id, full_text, is_resolved, channel, extra_parameters, timestamp, is_geolocated, location, epoch, reason) VALUES (1522017, e'Arkadaşımın anne babası enkaz altında. Acil vinç isteniyor.

Antakya/Hatay Akevler Mah. 424.sk. Melis Apt.

Erhan Tül: 0537 261 10 70
Büşra Tül: 0539 736 23 24
@ahbaphatay @ahbap @OguzhanUgur @AKUTASSOCIATION @haluklevent
 #deprem', false, 'twitter', '{''user_id'': 810194151518203904, ''screen_name'': ''metamelek31'', ''name'': ''Э'', ''tweet_id'': 1625220254019231764, ''created_at'': Timestamp(''2023-02-13 22:47:58''), ''hashtags'': [''deprem''], ''user_account_created_at'': ''Э'', ''media'': None}', '2023-02-13 20:05:16.213858 +00:00', false, null, 1676328478, null);
INSERT INTO public.feeds_entry (id, full_text, is_resolved, channel, extra_parameters, timestamp, is_geolocated, location, epoch, reason) VALUES (1522016, e'@haluklevent @ahbap Teyit edildi: 13 şubat saat 22:45’te
Kurulan çadır düşmüş 7kişi için acil çadır lazım .
Adres Dumlupınar mahallesi 78 nolu sk no 47 parkın önü Şahinbey Gaziantep
Telefon:+90 (534) 553 97 44
Buse Çiçek', false, 'twitter', '{''user_id'': 1397514920808402947, ''screen_name'': ''Alicakir190300'', ''name'': ''Ali'', ''tweet_id'': 1625222495593693184, ''created_at'': Timestamp(''2023-02-13 22:56:52''), ''hashtags'': None, ''user_account_created_at'': ''Ali'', ''media'': None}', '2023-02-13 20:04:53.445563 +00:00', false, null, 1676329012, null);
INSERT INTO public.feeds_entry (id, full_text, is_resolved, channel, extra_parameters, timestamp, is_geolocated, location, epoch, reason) VALUES (1522015, e'@Kandilli_info @forzabesiktas Teyit edildi: 13 şubat saat 22:45’te
Kurulan çadır düşmüş 7kişi için acil çadır lazım .
Adres Dumlupınar mahallesi 78 nolu sk no 47 parkın önü Şahinbey Gaziantep
Telefon:+90 (534) 553 97 44
Buse Çiçek', false, 'twitter', '{''user_id'': 1397514920808402947, ''screen_name'': ''Alicakir190300'', ''name'': ''Ali'', ''tweet_id'': 1625221201135018010, ''created_at'': Timestamp(''2023-02-13 22:51:44''), ''hashtags'': None, ''user_account_created_at'': ''Ali'', ''media'': None}', '2023-02-13 19:59:29.436155 +00:00', false, null, 1676328704, null);
INSERT INTO public.feeds_entry (id, full_text, is_resolved, channel, extra_parameters, timestamp, is_geolocated, location, epoch, reason) VALUES (1522014, e'@bulentuslu1903 @souza5 Teyit edildi: 13 şubat saat 22:45’te
Kurulan çadır düşmüş 7kişi için acil çadır lazım .
Adres Dumlupınar mahallesi 78 nolu sk no 47 parkın önü Şahinbey Gaziantep
Telefon:+90 (534) 553 97 44
Buse Çiçek
Abi yardımcı olabilirmisin lütfen', false, 'twitter', '{''user_id'': 1397514920808402947, ''screen_name'': ''Alicakir190300'', ''name'': ''Ali'', ''tweet_id'': 1625220797651361793, ''created_at'': Timestamp(''2023-02-13 22:50:07''), ''hashtags'': None, ''user_account_created_at'': ''Ali'', ''media'': None}', '2023-02-13 19:59:25.366176 +00:00', false, null, 1676328607, null);
INSERT INTO public.feeds_entry (id, full_text, is_resolved, channel, extra_parameters, timestamp, is_geolocated, location, epoch, reason) VALUES (1522013, e'Teyitli

Ferit Aydın Sokak, öğretmenevi yanı, Kız İmam Hatip Okulu, Birecik/Şanlıurfa

15 torunu olan 3 aile şu an okulda kalıyor. Aynı zamanda bebek ve down sendromlu bir birey de bulunuyor. Acilen bebek maması, bebek bezi, erzak ve kıyafet gerekiyor.

05362265453', false, 'twitter', '{''user_id'': 1345403943803879425, ''screen_name'': ''psychologist43'', ''name'': ''Ali Ψ'', ''tweet_id'': 1625220686129012741, ''created_at'': Timestamp(''2023-02-13 22:49:41''), ''hashtags'': None, ''user_account_created_at'': ''Ali Ψ'', ''media'': None}', '2023-02-13 19:59:16.076383 +00:00', false, null, 1676328581, null);
INSERT INTO public.feeds_entry (id, full_text, is_resolved, channel, extra_parameters, timestamp, is_geolocated, location, epoch, reason) VALUES (1522012, e'@BabalaTv Teyit edildi: 13 şubat saat 22:45’te
Kurulan çadır düşmüş 7kişi için acil çadır lazım .
Adres Dumlupınar mahallesi 78 nolu sk no 47 parkın önü Şahinbey Gaziantep
Telefon:+90 (534) 553 97 44
Buse Çiçek', false, 'twitter', '{''user_id'': 1397514920808402947, ''screen_name'': ''Alicakir190300'', ''name'': ''Ali'', ''tweet_id'': 1625220200629936139, ''created_at'': Timestamp(''2023-02-13 22:47:45''), ''hashtags'': None, ''user_account_created_at'': ''Ali'', ''media'': None}', '2023-02-13 19:59:13.132567 +00:00', false, null, 1676328465, null);
INSERT INTO public.feeds_entry (id, full_text, is_resolved, channel, extra_parameters, timestamp, is_geolocated, location, epoch, reason) VALUES (1522011, e'İrtibat: Resul sağır
0535 877 0401

Ürgenpaşa mah. Atatürk cad. Suphi karakaya apt no 67 hatay Antakya

Enkaz altında 25 kişiler, ses gelmiyor. Vinç, ekip ve kepçe gerekli

İrtibat saati:21:40', false, 'twitter', '{''user_id'': 2790646610, ''screen_name'': ''unigfbizmir'', ''name'': ''UNIGFB İzmir'', ''tweet_id'': 1625221973272829968, ''created_at'': Timestamp(''2023-02-13 22:54:48''), ''hashtags'': None, ''user_account_created_at'': ''UNIGFB İzmir'', ''media'': None}', '2023-02-13 19:58:54.660250 +00:00', false, null, 1676328888, null);


-- Feeds Location
INSERT INTO public.feeds_location (id, formatted_address, latitude, longitude, northeast_lat, northeast_lng, southwest_lat, southwest_lng, entry_id, timestamp, epoch, reason, channel, extra_parameters, is_location_verified, is_need_verified, is_deleted) VALUES (239734, 'Akbez, Zümrüt Cd. No:11, 31700 Hassa/Hatay, Türkiye', 36.8471369, 36.5600994, 36.84848672989272, 36.56144922989272, 36.84578707010727, 36.55874957010727, 1522034, '0001-01-01 00:00:00.000000 +00:00', 1676329056, 'barinma', 'twitter', null, false, false, false);
INSERT INTO public.feeds_location (id, formatted_address, latitude, longitude, northeast_lat, northeast_lng, southwest_lat, southwest_lng, entry_id, timestamp, epoch, reason, channel, extra_parameters, is_location_verified, is_need_verified, is_deleted) VALUES (239735, 'Sanayi, 60011. Cd. No:47, 27000 Şehitkamil/Gaziantep, Türkiye', 37.0787124, 37.4378028, 37.08001932989272, 37.43920287989273, 37.07731967010728, 37.43650322010728, 1522035, '0001-01-01 00:00:00.000000 +00:00', 1676329144, 'barinma', 'twitter', null, false, false, false);
INSERT INTO public.feeds_location (id, formatted_address, latitude, longitude, northeast_lat, northeast_lng, southwest_lat, southwest_lng, entry_id, timestamp, epoch, reason, channel, extra_parameters, is_location_verified, is_need_verified, is_deleted) VALUES (239737, 'Siteler, 20132. Sk., 02200 Adıyaman Merkez/Adıyaman, Türkiye', 37.770528, 38.2975527, 37.77187782989272, 38.29890252989272, 37.76917817010727, 38.29620287010727, 1522037, '0001-01-01 00:00:00.000000 +00:00', 1676329311, '', 'twitter', null, false, false, false);
INSERT INTO public.feeds_location (id, formatted_address, latitude, longitude, northeast_lat, northeast_lng, southwest_lat, southwest_lng, entry_id, timestamp, epoch, reason, channel, extra_parameters, is_location_verified, is_need_verified, is_deleted) VALUES (239738, 'Sanayi, 60011. Cd. No:47, 27000 Şehitkamil/Gaziantep, Türkiye', 37.0787124, 37.4378028, 37.08001932989272, 37.43920287989273, 37.07731967010728, 37.43650322010728, 1522038, '0001-01-01 00:00:00.000000 +00:00', 1676329469, '', 'twitter', null, false, false, false);
INSERT INTO public.feeds_location (id, formatted_address, latitude, longitude, northeast_lat, northeast_lng, southwest_lat, southwest_lng, entry_id, timestamp, epoch, reason, channel, extra_parameters, is_location_verified, is_need_verified, is_deleted) VALUES (239739, 'Bozbey Cd., Adıyaman Merkez/Adıyaman, Türkiye', 37.7575055, 38.2593486, 37.75885532989273, 38.26069842989271, 37.75615567010728, 38.25799877010727, 1522039, '0001-01-01 00:00:00.000000 +00:00', 1676329426, '', 'twitter', null, false, false, false);
INSERT INTO public.feeds_location (id, formatted_address, latitude, longitude, northeast_lat, northeast_lng, southwest_lat, southwest_lng, entry_id, timestamp, epoch, reason, channel, extra_parameters, is_location_verified, is_need_verified, is_deleted) VALUES (239740, 'Sanayi, 60011. Cd. No:47, 27000 Şehitkamil/Gaziantep, Türkiye', 37.0787124, 37.4378028, 37.08001932989272, 37.43920287989273, 37.07731967010728, 37.43650322010728, 1522040, '0001-01-01 00:00:00.000000 +00:00', 1676329070, 'barinma', 'twitter', null, false, false, false);
INSERT INTO public.feeds_location (id, formatted_address, latitude, longitude, northeast_lat, northeast_lng, southwest_lat, southwest_lng, entry_id, timestamp, epoch, reason, channel, extra_parameters, is_location_verified, is_need_verified, is_deleted) VALUES (239741, 'Sanayi, 60011. Cd. No:47, 27000 Şehitkamil/Gaziantep, Türkiye', 37.0787124, 37.4378028, 37.08001932989272, 37.43920287989273, 37.07731967010728, 37.43650322010728, 1522041, '0001-01-01 00:00:00.000000 +00:00', 1676329169, 'barinma', 'twitter', null, false, false, false);
INSERT INTO public.feeds_location (id, formatted_address, latitude, longitude, northeast_lat, northeast_lng, southwest_lat, southwest_lng, entry_id, timestamp, epoch, reason, channel, extra_parameters, is_location_verified, is_need_verified, is_deleted) VALUES (239742, 'Karacasu Mamaraş, 84041. Sokak No: 41, 46100 Dulkadiroğlu/Kahramanmaraş, Türkiye', 37.5061213, 36.9925833, 37.50746802989273, 36.99398292989272, 37.50476837010728, 36.99128327010727, 1522042, '0001-01-01 00:00:00.000000 +00:00', 1676329227, 'barinma', 'twitter', null, false, false, false);
INSERT INTO public.feeds_location (id, formatted_address, latitude, longitude, northeast_lat, northeast_lng, southwest_lat, southwest_lng, entry_id, timestamp, epoch, reason, channel, extra_parameters, is_location_verified, is_need_verified, is_deleted) VALUES (239743, 'Sanayi, 60011. Cd. No:47, 27000 Şehitkamil/Gaziantep, Türkiye', 37.0787124, 37.4378028, 37.08001932989272, 37.43920287989273, 37.07731967010728, 37.43650322010728, 1522043, '0001-01-01 00:00:00.000000 +00:00', 1676329348, 'barinma', 'twitter', null, false, false, false);
